### ISSUE TITLE
 Fatal error: Redefinition of parameter $address in /Trustly/Api/signed.php on line 854

### ISSUE THREAD

**Issue by rodrigoaguilera** [trustly/trustly-client-php#10]
https://github.com/trustly/trustly-client-php/blob/master/Trustly/Api/signed.php#L854

The address parameter is twice there, on line 856 and 860.

Do you plan on including tests so this trivial mistake doesn't happen?

**Comment by Pelleplutt** [comment]
Fixed.

Tests are planned. But keep in mind this is an example implementation code, provided as is. Not sure this type of problem would would not have been caught in normal code tests as PHP on older versions gladly accepted this.

**Comment by MikeLund** [comment]
That is kinda the whole purpose of tests though. You can very easily see if there is any major things that might go wrong with a newer environment without sacrificing too much time. :)
