### ISSUE TITLE
Possibility to search for specific payment

### ISSUE THREAD

**Issue by TXC** [trustly/trustly-client-php#2]
Would be great with the ability to search the account ledger for a payment and get the current status of a specific payment and to verify that it exist.

**Comment by Pelleplutt** [comment]
Sorry for my poor suport there. For some reason this got left behind.

We have some specific calls that are created for specific types of integrations as these calls are not a part of the general API they are not linked on the overall developer portal. As such they are not included in this example library either until the point where they are made available for everybody.

Having that said however all the function calls to the API are fairly simple and straightforward, adding this call by yourself should be a 5min feat as the functions in Api/signed are more or less only a mapping between function arguments and the data structure in the call, in this case it will be 3 fields that you need to add.
