### ISSUE TITLE
PHPDoc on all methods for better IDE integration

### ISSUE THREAD

**Issue by TXC** [trustly/trustly-client-php#3]
Would be nice with PHPDoc on all methods for integration with IDEs.

**Comment by lucasgranberg** [comment]
I agree, also PSR-4 compliance with proper namespaces would be nice. You could also go for Guzzle while you are at it. Borrow some ideas from here: https://github.com/nordsoftware/paytrail-php :smirk:

**Comment by Pelleplutt** [comment]
@lucasgranberg  adding namespaces would require PHP 5.3.0 we still have a lot of merchants running 5.2.0 at this point so I cannot add that at this point I am afraid.

**Comment by lucasgranberg** [comment]
You could just create a new branch. PHP 5.2 is end of life since almost 5 years ago. http://php.net/eol.php

**Comment by Pelleplutt** [comment]
@lucasgranberg thank you, I have heard about these things called branches ;-) but at this time I will not do this.
